name: vibetag
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.17.0
  typicons_flutter: ^0.3.1

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - images/path.jpg
    - images/man_pic.jpg
    - images/logo.jpg
    - images/photoFollow.jpg
  fonts:
    - family: Helvetica Neue
      fonts:
        - asset: fonts/HelveticaNeue.ttf
        - asset: fonts/HelveticaNeuBold.ttf
          weight: 700
    - family: Helvetica Neue
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
